server:
  port: 10500
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root
  application:
    name: gatewey
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order
