spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: root
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: AA



#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:10000/eureka

server:
  port: 9000