spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      discovery:
        cluster-name: AA
        ephemeral: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:10000/eureka
user-service:
  ribbon:
    NFLoadBalancingRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

user:
  a: 123

server:
  port: 9500

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

