server:
  port: 10000
spring:
  application:
    name: eureka-server
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka


