spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
    virtual-host: /
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: root
server:
  port: 11000